name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      HF_USER: tonystark0
      HF_SPACE: machine-translation
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote 
        run: git remote add space https://${{ env.HF_USER }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ env.HF_USER }}/${{ env.HF_SPACE }}
      - name: Push to hub
        run: git push --force https://${{ env.HF_USER }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ env.HF_USER }}/${{ env.HF_SPACE }} main